# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-04 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=250)),
                ('body', models.TextField()),
                ('price', models.FloatField()),
                ('date_create', models.DateField(auto_now_add=True)),
                ('last_changes', models.DateField(auto_now=True)),
                ('customers', models.ManyToManyField(to='Client.Client')),
            ],
        ),
    ]
